name: Run Script on Push

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

# Job definition
jobs:
  run-script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Execute script.sh
      run: |
        chmod +x ./script.sh
        ./script.sh
