name: SHA verifier for quay and repo

on:
  schedule:
    - cron: '* * * * *' 
  workflow_dispatch:
   inputs:
      branch_name:
        description: 'Branch Name to Run the Script On'
        required: true
        default: 'main'
    

# Job 
jobs:
  run-script:
    runs-on: ubuntu-latest

    # Steps
    steps:
    - uses: actions/checkout@v3

    - name: Execute sha_update.sh
      run: |
        chmod +x ./sha_update.sh
        ./sha_update.sh
