name: Clone Specific Repo and Branch

on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'Repository URL'
        required: true
      branch_name:
        description: 'Branch Name'
        required: true

jobs:
  clone-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Custom Script
        run: |
          chmod +x ./path/to/your/branch.sh
          ./path/to/your/script.sh ${{ github.event.inputs.repository_url }} ${{ github.event.inputs.branch_name }}
