name: Clone Specific Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name'
        required: true

jobs:
  clone-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Custom Script
        run: |
          chmod +x ./branch.sh
          ./branch.sh "${{ github.event.inputs.branch_name }}"
