name: Branch check

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL (leave blank to use repo_url.txt)'
        required: false
      branch_name:
        description: 'Branch Name to Run the Script On (leave blank to use branch_name.txt)'
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # If the repo_url is provided, overwrite repo_url.txt
    - name: Set Repository URL
      if: ${{ github.event.inputs.repo_url }}
      run: echo "${{ github.event.inputs.repo_url }}" > repo_url.txt

    # If the branch_name is provided, overwrite branch_name.txt
    - name: Set Branch Name
      if: ${{ github.event.inputs.branch_name }}
      run: echo "${{ github.event.inputs.branch_name }}" > branch_name.txt

    - name: Execute sha_update.sh
      run: |
        chmod +x ./sha_update.sh
        ./sha_update.sh
