name: Verify and Process Branch

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name (leave empty to use the default branch)'
        required: false
        default: ''

jobs:
  process-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.event.inputs.branch_name || github.event.repository.default_branch }}

      - name: Run Script
        run: |
          chmod +x ./branch.sh
          ./branch.sh "${{ github.event.inputs.branch_name || github.event.repository.default_branch }}"
