name: Process Branch with Optional Selection

on:
  schedule:
    # Runs at 00:00 UTC every day on the default branch
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name (leave empty to use the default branch)'
        required: false
        default: ''

jobs:
  process-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Use the input branch name if provided, otherwise fallback to the default branch.
          # This effectively makes the branch name optional for manual triggers.
          ref: ${{ github.event.inputs.branch_name || github.ref_name }}

      - name: Set up Git Debug Logging
        run: |
          git config --global --add protocol.version 2
          git config --global core.logAllRefUpdates true
          export GIT_TRACE=1
          export GIT_CURL_VERBOSE=1

      - name: Attempt Fetch (Debug)
        run: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1

      - name: Run Script
        run: |
          chmod +x ./branch1.sh
          # Pass the branch name to the script. If it's a schedule event, this will be empty and can be handled by the script accordingly.
          ./branch1.sh "${{ github.event.inputs.branch_name || github.ref_name }}"
