name: Dynamic Fetch Branches and Tags

on:
  workflow_dispatch:
    inputs:
      pattern:
        description: 'Branch/Tag pattern to fetch (e.g., feature-*, release-2.1*)'
        required: true
        default: 'main'

jobs:
  fetch-branches-and-tags:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags.
      
      - name: Configure Git
        run: |
          git config --global --add protocol.version 2
          git config --global core.logAllRefUpdates true
      
      - name: Fetch Based on Pattern
        run: |
          PATTERN="${{ github.event.inputs.pattern }}"
          echo "Fetching branches and tags matching the pattern '$PATTERN'..."
          
          if git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/$PATTERN:refs/remotes/origin/$PATTERN +refs/tags/$PATTERN:refs/tags/$PATTERN; then
            echo "Successfully fetched branches and tags matching the pattern '$PATTERN'."
          else
            echo "Failed to fetch branches or tags matching the pattern '$PATTERN'. Please check the pattern and ensure matching branches/tags exist."
          fi
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
