name: Verify and Process Branch

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name (leave empty to use the default branch)'
        required: false
        default: ''

jobs:
  process-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NEW }}
          ref: ${{ github.event.inputs.branch_name || github.event.repository.default_branch }}
      - name: Set up Git Debug Logging
        run: |
          git config --global --add protocol.version 2
          git config --global core.logAllRefUpdates true
          export GIT_TRACE=1
          export GIT_CURL_VERBOSE=1

      - name: Attempt Fetch (Debug)
        run: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/rhoai-2.9*:refs/remotes/origin/rhoai-2.9* +refs/tags/rhoai-2.9*:refs/tags/rhoai-2.9*
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1

      - name: Run Script
        run: |
          chmod +x ./branch.sh
          ./branch.sh "${{ github.event.inputs.branch_name || github.event.repository.default_branch }}"
