name: test

on:
schedule:
  - cron: '20 30 * * *' 
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name'
        required: true

jobs:
  clone-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Run Custom Script
        run: |
          chmod +x ./test.sh
          ./test.sh "${{ github.event.inputs.branch_name }}"
